provide geocoordinates for projects
justimmo/php-sdk pull request #100
Opened 2018-08-28 07:55 UTC by infabo

2018-09-03 09:36 UTC, 19Gerhard85 requested changes

2018-09-03 09:36 UTC, 19Gerhard85 commented on src/Justimmo/Model/Project.php
> +        $this->latitude = $latitude;
Please add a new line.

2018-09-03 09:36 UTC, 19Gerhard85 commented on src/Justimmo/Model/Project.php
> +        $this->longitude = $longitude;
Please add a new line.

2018-09-03 09:36 UTC, 19Gerhard85 commented on src/Justimmo/Model/Wrapper/V1/ProjectWrapper.php
> +            $project->setLatitude((float) $coord['breitengrad']);
Please cast to (double)

2018-09-03 09:36 UTC, 19Gerhard85 commented on src/Justimmo/Model/Wrapper/V1/ProjectWrapper.php
> +            $project->setLongitude((float) $coord['laengengrad']);
Please cast to (double)

2018-09-03 14:58 UTC, infabo commented
resolved requested changes.

2018-09-04 04:56 UTC, 19Gerhard85 approved these changes

2018-09-04 13:46 UTC, merged