Building progress
justimmo/php-sdk pull request #88
Opened 2018-06-15 10:47 UTC by zoltan-sule

Implements:
- changes the column from Delegated to Relation
- moves completion date into BuildingProgress
- adds BuildingProgressRequest
- unittests

related to [Objektdetailseite / Basisdaten Projekte ](https://github.com/justimmo/websites/issues/237)

2018-06-15 11:15 UTC, simitter requested changes

2018-06-15 11:15 UTC, Tschebel commented on src/Entity/Realty/BuildingProgress.php
> + * @JUSTIMMO\Entity(cacheKey="buildingProgress")
The cacheKey should contain a property name. In this case it would be id.

2018-06-15 11:15 UTC, Tschebel commented on src/Request/BuildingProgressRequest.php
> +class BuildingProgressRequest extends BaseApiRequest
There is no api call to fetch the building progress. This request would always return a 404.

2018-06-15 11:22 UTC, simitter requested changes

2018-06-15 11:22 UTC, Tschebel commented on tests/Request/RealtyRequestTest.php
> +    public function testBuildingProgress()
Should not be neccessary. The test buildingProgress ist tested automatically, becaus it's defined in the FIELD constant.
You only have to add own tests for custom methods on the request (see testShortcutMarketingStates method in this class)

2018-06-15 14:40 UTC, zoltan-sule commented
erledigt

2018-06-18 07:57 UTC, simitter approved these changes

2018-06-19 12:00 UTC, merged